name: Extract and Push HTML

on:
  schedule:
    - cron: "0 8 * * *"  # Daily at 8 AM UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run parser
        run: |
          python scripts/scrape_events.py > index.html

      - name: Create orphan branch and push HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a new orphan branch
          git checkout --orphan gh-pages

          # Add and commit
          git add index.html
          git commit -m "Add extracted HTML output"

          # Force-push to overwrite the branch
          git push -f origin gh-pages
